# Generated by Django 3.0.2 on 2020-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDataBase',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10, null=True)),
                ('owner', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
