# Generated by Django 3.0.2 on 2020-01-28 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesDataBase',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=10)),
                ('owner', models.IntegerField(blank=True)),
            ],
        ),
    ]
