# Generated by Django 3.0.2 on 2020-01-28 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
