# Generated by Django 3.0.2 on 2020-01-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200128_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='owner',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='state',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
