# Generated by Django 3.0.2 on 2020-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200128_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='owner',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
