# Generated by Django 3.0.2 on 2020-01-30 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200128_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
