# Generated by Django 3.0.2 on 2020-01-30 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200130_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdatabase',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
    ]
